#!/bin/sh

set -e 

for f in *.diff; do
	echo -n "$f ... "
	sed -n 's/^# //gp' $f | awk '
	BEGIN { horigin="0"; hcset="0"; hinclusion="0"; hdescription="0"; hrevdate="0"; herror="0"; }
	/^origin:/ { horigin="1"; }
	/^cset:/ { hcset="1"; }
	/^inclusion:/ { hinclusion="1"; }
	/^description:/ { hdescription="1"; }
	/^revision date:/ { hrevdate="1"; }
	END {
		if (horigin == "0") { herror="1"; print "missing: origin "; }
		if (hcset == "0") { herror="1"; print "missing: cset "; }
		if (hinclusion == "0") { herror="1"; print "missing: inclusion "; }
		if (hdescription == "0") { herror="1"; print "missing: description "; }
		if (hrevdate == "0") { herror="1"; print "missing: hrevdate "; }
		if (herror == "1") { print "Some fields are missing from this diff"; exit 1; }
		else { print "OK" }
	}'
done

# vim:ai:ts=4:noet
