#!/bin/bash
set -e

#http_proxy=http://proxyserver:3128
#ftp_proxy=http://proxyserver:3128
#export http_proxy ftp_proxy

VERSION_DEBIAN="${1}"
VERSION="${2}"
VERSION_DEBIAN_BINNMU="${3}"

MAJOR_VER="${VERSION%\~*}"
RC_VER="${VERSION#*\~}"
[ "x${MAJOR_VER}" = "x${RC_VER}" ] && RC_VER=""

TMP_DIR="$(mktemp -d -p /tmp linux-sidux-2.6.XXXXXX)"
pushd "${TMP_DIR}"
	if [ -z "$RC_VER" ]; then
		# stable kernel
		UP_TARBALL="linux-${MAJOR_VER}.tar.bz2"
		ORIG_TARBALL="linux-sidux-2.6_${MAJOR_VER}.orig.tar.bz2"
		wget -Nc "http://www.kernel.org/pub/linux/kernel/v2.6/${UP_TARBALL}"
	else
		# rc kernel
		UP_TARBALL="linux-${MAJOR_VER}-${RC_VER}.tar.bz2"
		ORIG_TARBALL="linux-sidux-2.6_${MAJOR_VER}~${RC_VER}.orig.tar.bz2"
		wget -Nc "http://www.kernel.org/pub/linux/kernel/v2.6/testing/${UP_TARBALL}"
	fi
popd >/dev/null 2>&1

mkdir "${TMP_DIR}/linux-${VERSION}"
pushd "${TMP_DIR}/linux-${VERSION}" >/dev/null 2>&1
	tar --strip 1 -xjf "${TMP_DIR}/${UP_TARBALL}"
	rm "${TMP_DIR}/${UP_TARBALL}"

	# remove shipped firmware images
	rm -rf	firmware \
		sound/pci/cs46xx/imgs

	# remove individual blobby files throughout the tree
	rm	Documentation/netlabel/draft-ietf-cipso-ipsecurity-01.txt \
		arch/powerpc/sysdev/micropatch.c \
		drivers/media/dvb/dvb-usb/af9005-script.h \
		drivers/infiniband/hw/ipath/ipath_sd7220_img.c \
		drivers/net/appletalk/cops.c \
		drivers/net/appletalk/cops.h \
		drivers/net/appletalk/cops_ffdrv.h \
		drivers/net/appletalk/cops_ltdrv.h \
		drivers/staging/otus/hal/hp*fw*.c* \
		drivers/staging/rt2860/common/firmware.h \
		drivers/staging/rt2860/common/firmware_3070.h \
		drivers/staging/rt3070/firmware.h \
		drivers/staging/rt3090/firmware.h \
		drivers/staging/rtl8192su/r8192SU_HWImg.c \
		drivers/staging/rtl8192u/r819xU_firmware_img.c \
		drivers/staging/vt6656/firmware.c \
		sound/pci/cs46xx/cs46xx_image.h

	#unifdef drivers/media/dvb/frontends/lgs8gxx.c -UREMOVE_DFSG
	[ "x$(md5sum -b drivers/media/dvb/frontends/lgs8gxx.c | awk '{print $1}')" = "xca65e6b0884790662e180e6f250e0ef1" ] || false
	sed -i	-e '49,84d' \
			drivers/media/dvb/frontends/lgs8gxx.c

	#unifdef drivers/net/r8169.c -UREMOVE_DFSG
	[ "x$(md5sum -b drivers/net/r8169.c | awk '{print $1}')" = "x95021e3fb35da2bb1e2e7aee3687c406" ] || false
	sed -i	-e '1722,2076d' \
		-e '2164,2475d' \
			drivers/net/r8169.c

	echo "mark pruned modules as BROKEN"
	patch -p1 < ${0%$(basename $0)}/../patches/dfsg/orig/disable-pruned-modules.patch
popd >/dev/null 2>&1

pushd "${TMP_DIR}" >/dev/null 2>&1
	tar	\
		--exclude \*\\.orig \
		--posix \
		--numeric-owner \
		--owner=0 \
		--group=0 \
		-cjf "${TMP_DIR}/${ORIG_TARBALL}" \
			"linux-${VERSION}"

	rm -rf ${TMP_DIR}/linux-${VERSION}
popd >/dev/null 2>&1

echo "COMPLETED: ${TMP_DIR}/${ORIG_TARBALL}"
