#!/bin/bash
set -e

#http_proxy=http://proxyserver.lan:3128
#ftp_proxy=http://proxyserver.lan:3128
#export http_proxy ftp_proxy

VERSION_DEBIAN="${1}"
VERSION="${2}"
VERSION_DEBIAN_BINNMU="${3}"

MAJOR_VER="${VERSION%\~*}"
RC_VER="${VERSION#*\~}"
[ "x${MAJOR_VER}" = "x${RC_VER}" ] && RC_VER=""

TMP_DIR="$(mktemp -d -p /tmp linux-aptosid-2.6.XXXXXX)"
pushd "${TMP_DIR}"
	if [ -z "$RC_VER" ]; then
		# stable kernel
		UP_TARBALL="linux-${MAJOR_VER}.tar.bz2"
		ORIG_TARBALL="linux-aptosid-2.6_${MAJOR_VER}.orig.tar.bz2"
		wget -Nc "http://www.kernel.org/pub/linux/kernel/v2.6/${UP_TARBALL}"
	else
		# rc kernel
		UP_TARBALL="linux-${MAJOR_VER}-${RC_VER}.tar.bz2"
		ORIG_TARBALL="linux-aptosid-2.6_${MAJOR_VER}~${RC_VER}.orig.tar.bz2"
		wget -Nc "http://www.kernel.org/pub/linux/kernel/v2.6/testing/${UP_TARBALL}"
	fi
popd >/dev/null 2>&1

mkdir "${TMP_DIR}/linux-${VERSION}"
pushd "${TMP_DIR}/linux-${VERSION}" >/dev/null 2>&1
	tar --strip 1 -xjf "${TMP_DIR}/${UP_TARBALL}"
	rm "${TMP_DIR}/${UP_TARBALL}"

	# remove shipped firmware images
	rm -rf	firmware \
		sound/pci/cs46xx/imgs

	# remove individual blobby files throughout the tree
	rm	Documentation/netlabel/draft-ietf-cipso-ipsecurity-01.txt \
		arch/powerpc/sysdev/micropatch.c \
		drivers/media/dvb/dvb-usb/af9005-script.h \
		drivers/net/appletalk/cops.c \
		drivers/net/appletalk/cops.h \
		drivers/net/appletalk/cops_ffdrv.h \
		drivers/net/appletalk/cops_ltdrv.h \
		drivers/staging/otus/hal/hp*fw*.c* \
		drivers/staging/vt6656/firmware.c \
		drivers/staging/wlags49_h2/ap_h2.c \
		drivers/staging/wlags49_h2/ap_h25.c \
		drivers/staging/wlags49_h2/sta_h2.c \
		drivers/staging/wlags49_h2/sta_h25.c \
		sound/pci/cs46xx/cs46xx_image.h

	#unifdef drivers/net/r8169.c -UREMOVE_DFSG
	[ "x$(md5sum -b drivers/net/r8169.c | awk '{print $1}')" = "xb69004175836afe2789bb416f3664449" ] || false
	sed -i	-e '1749,2103d' \
		-e '2191,2502d' \
			drivers/net/r8169.c

	#unifdef drivers/staging/rtl8192u/r819xU_firmware_img.c -UREMOVE_DFSG
	[ "x$(md5sum -b drivers/staging/rtl8192u/r819xU_firmware_img.c | awk '{print $1}')" = "xa1ea5f269229fe028cb347cc5f76a6c3" ] || false
	sed -i	-e '4,2902d' \
			drivers/staging/rtl8192u/r819xU_firmware_img.c

	echo "mark pruned modules as BROKEN"
	patch -p1 < ${0%$(basename $0)}/../patches/dfsg/orig/disable-pruned-modules.patch
popd >/dev/null 2>&1

pushd "${TMP_DIR}" >/dev/null 2>&1
	tar	\
		--exclude \*\\.orig \
		--posix \
		--numeric-owner \
		--owner=0 \
		--group=0 \
		-cjf "${TMP_DIR}/${ORIG_TARBALL}" \
			"linux-${VERSION}"

	rm -rf ${TMP_DIR}/linux-${VERSION}
popd >/dev/null 2>&1

echo "COMPLETED: ${TMP_DIR}/${ORIG_TARBALL}"
